import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

import Footer from "../components/commons/footer";
import Header from "../components/commons/header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lang } }) {
  return (
    <html lang={lang}>
      <body className={`${inter.className} selection:bg-fuchsia-300 selection:text-fuchsia-900`}>
        <Header />
        {children}
        <Footer lang={lang} />
      </body>
    </html>
  );
}

